include:
  - ".well-known"
layout: post
title: "Haley Art House"
description: "Art!"
url: "https://HaleyArtHouse.com"
image: "/HaleyArtHouse.PNG"
logo: "/HaleyArtHouse.PNG"
alt: "Haley Art House Logo"
